export const PostsData = [
    {
        caption: "This is a remedy for Fever generated by GPT",
        instructions: "Mix 1 teaspoon each of Holy Basil (Tulsi), Cinnamon and Cloves powder and take with lukewarm water twice a day until fever subsides.",
        herbs: [
            "Holy Basil (Tulsi)",
            "Cinnamon",
            "Cloves"
        ],
        ailments: [
            "fever"
        ],
        image: "./r1.png",
        totalreviews: 0,
        starreview: 0,
        _id: "644c9a7594c1eae4bc8a5539"
    },
    {
        caption: "This is a remedy for Fever generated by GPT",
        instructions: "Mix 1 teaspoon each of Holy Basil (Tulsi), Cinnamon and Cloves powder and take with lukewarm water twice a day until fever subsides.",
        herbs: [
            "Holy Basil (Tulsi)",
            "Cinnamon",
            "Cloves"
        ],
        ailments: [
            "fever"
        ],
        image: "./r1.png",
        totalreviews: 0,
        starreview: 0,
        _id: "644c9a7594c1eae4bc8a5539"
    },
    {
        caption: "This is a remedy for Fever generated by GPT",
        instructions: "Mix 1 teaspoon each of Holy Basil (Tulsi), Cinnamon and Cloves powder and take with lukewarm water twice a day until fever subsides.",
        herbs: [
            "Holy Basil (Tulsi)",
            "Cinnamon",
            "Cloves"
        ],
        ailments: [
            "fever"
        ],
        image: "./r1.png",
        totalreviews: 0,
        starreview: 0,
        _id: "644c9a7594c1eae4bc8a5539"
    },
    {
        caption: "This is a remedy for Fever generated by GPT",
        instructions: "Mix 1 teaspoon each of Holy Basil (Tulsi), Cinnamon and Cloves powder and take with lukewarm water twice a day until fever subsides.",
        herbs: [
            "Holy Basil (Tulsi)",
            "Cinnamon",
            "Cloves"
        ],
        ailments: [
            "fever"
        ],
        image: "./r1.png",
        totalreviews: 0,
        starreview: 0,
        _id: "644c9a7594c1eae4bc8a5539"
    }
]